# Generated by Django 6.0.5 on 2026-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
