# Generated by Django 5.2.8 on 2026-05-21 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_media_url_chat_message_type_alter_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chat'),
        ),
    ]
