# Generated by Django 6.0.5 on 2026-05-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
