# Generated by Django 6.0.5 on 2026-05-30 13:01

import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=stories.models.story_media_upload_path),
        ),
    ]
